# Docker Compose File: Nextcloud Private Cloud Lab
# Version 3 is the standard for engine compatibility
version: '3'

services:
  # DATABASE SERVICE:
  db:
    image: mariadb:10.6  # Lightweight, open-source SQL database
    restart: always      # Security/Reliability: Service restarts automatically after a crash or system reboot
    
    # Nextcloud specific DB requirements for data integrity
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    
    volumes:
      - db_data:/var/lib/mysql  # Persistent Storage: Maps internal DB data to a named volume on the host
      
    environment:
      # REDACTED FOR GITHUB: Use environment variables or a .env file in production
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}  # Admin password for the database engine
      - MYSQL_PASSWORD=${DB_USER_PASSWORD}      # Standard user password for Nextcloud to use
      - MYSQL_DATABASE=nextcloud                 # The name of the specific DB to be created
      - MYSQL_USER=nextcloud                     # The DB user for the app to authenticate with

  # APPLICATION SERVICE: The 'Face' of the operation (Web Interface)
  app:
    image: nextcloud
    restart: always
    
    ports:
      # [HOST PORT] : [CONTAINER PORT]
      # 8080: Maps the laptop's port to the internal container port 80
      - 8080:80
      
    links:
      - db  # Networking: Allows the app container to "see" the db container by name
      
    volumes:
      - nextcloud_data:/var/www/html  # Persistent Storage: Holds all uploaded photos/videos/files
      
    environment:
      # Credentials must match the DB service above to establish a connection
      - MYSQL_PASSWORD=${DB_USER_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db  # Tells Nextcloud to look for the 'db' service name on the internal Docker network

# VOLUME DEFINITION: Ensuring data survives even if the containers are deleted
volumes:
  db_data:        # Stores the SQL tables
  nextcloud_data: # Stores the actual media files